-- int residenitial inside x64c > levels > interiors > int_props

--<Item>v_bar</Item>
--<Item>v_bathroom</Item>
--<Item>v_electrical</Item>
--<Item>v_kitchen</Item>
--<Item>v_office</Item>




sofas = {
	[1] = { ["object"] = "miss_rub_couch_01", ["price"] = 300, ["name"] = "Old Flowered Couch" },
	[2] = { ["object"] = "prop_fib_3b_bench", ["price"] = 700, ["name"] = "3 Seat Chair" },
	[3] = { ["object"] = "prop_ld_farm_chair01", ["price"] = 250, ["name"] = "Old 1 Seat Couch" },
	[4] = { ["object"] = "prop_ld_farm_couch01", ["price"] = 300, ["name"] = "Old 3 Seat Couch" },
	[5] = { ["object"] = "prop_ld_farm_couch02", ["price"] = 300, ["name"] = "Old Striped Couch" },
	[6] = { ["object"] = "v_res_d_armchair", ["price"] = 300, ["name"] = "Old 1 Seat Couch Yellow" },
	[7] = { ["object"] = "v_res_fh_sofa", ["price"] = 3700, ["name"] = "Corner Sofa" },
	[8] = { ["object"] = "v_res_mp_sofa", ["price"] = 3700, ["name"] = "Corner Sofa 2" },
	[9] = { ["object"] = "v_res_d_sofa", ["price"] = 700, ["name"] = "Sofa 1" },
	[10] = { ["object"] = "v_res_j_sofa", ["price"] = 700, ["name"] = "Sofa 2" },
	[11] = { ["object"] = "v_res_mp_stripchair", ["price"] = 700, ["name"] = "Sofa 3" },
	[12] = { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 700, ["name"] = "Sofa 4" },
	[13] = { ["object"] = "v_res_r_sofa", ["price"] = 700, ["name"] = "Sofa 5" },
	[14] = { ["object"] = "v_res_tre_sofa", ["price"] = 700, ["name"] = "Sofa 6" },
	[15] = { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 700, ["name"] = "Sofa 7" },
	[16] = { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 700, ["name"] = "Sofa 8" },
	[17] = { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 700, ["name"] = "Sofa 9" },
	[18] = { ["object"] = "v_res_tt_sofa", ["price"] = 700, ["name"] = "Sofa 10" },
	[19] = { ["object"] = "prop_rub_couch02", ["price"] = 700, ["name"] = "Sofa 11" },
}

chairs = {
	[1] = { ["object"] = "v_res_d_highchair", ["price"] = 700, ["name"] = "High Chair" },
	[2] = { ["object"] = "v_res_fa_chair01", ["price"] = 700, ["name"] = "Chair" },
	[3] = { ["object"] = "v_res_fa_chair02", ["price"] = 700, ["name"] = "Chair" },
	[4] = { ["object"] = "v_res_fh_barcchair", ["price"] = 700, ["name"] = "High Chair" },
	[5] = { ["object"] = "v_res_fh_dineeamesa", ["price"] = 700, ["name"] = "Dine Chair 1" },
	[6] = { ["object"] = "v_res_fh_dineeamesb", ["price"] = 700, ["name"] = "Dine Chair 2" },
	[7] = { ["object"] = "v_res_fh_dineeamesc", ["price"] = 700, ["name"] = "Dine Chair 3" },
	[8] = { ["object"] = "v_res_fh_easychair", ["price"] = 700, ["name"] = "Chair" },
	[9] = { ["object"] = "v_res_fh_kitnstool", ["price"] = 700, ["name"] = "Stool" },
	[10] = { ["object"] = "v_res_fh_singleseat", ["price"] = 700, ["name"] = "High Chair" },
	[11] = { ["object"] = "v_res_jarmchair", ["price"] = 700, ["name"] = "Arm Chair" },
	[12] = { ["object"] = "v_res_j_dinechair", ["price"] = 700, ["name"] = "Dining Chair" },
	[13] = { ["object"] = "v_res_j_stool", ["price"] = 700, ["name"] = "Stool" },
	[14] = { ["object"] = "v_res_mbchair", ["price"] = 700, ["name"] = "MB Chair" },
	[15] = { ["object"] = "v_res_m_armchair", ["price"] = 700, ["name"] = "Arm Chair" },
	[16] = { ["object"] = "v_res_m_dinechair", ["price"] = 700, ["name"] = "Dine Chair" },
	[17] = { ["object"] = "v_res_study_chair", ["price"] = 700, ["name"] = "Study Chair" },
	[18] = { ["object"] = "v_res_trev_framechair", ["price"] = 700, ["name"] = "Frame Chair" },
	[19] = { ["object"] = "v_res_tre_chair", ["price"] = 700, ["name"] = "Chair" },
	[20] = { ["object"] = "v_res_tre_officechair", ["price"] = 700, ["name"] = "Office Chair" },
	[21] = { ["object"] = "v_res_tre_stool", ["price"] = 700, ["name"] = "Stool" },
	[22] = { ["object"] = "v_res_tre_stool_leather", ["price"] = 700, ["name"] = "Stool Leather" },
	[23] = { ["object"] = "v_res_tre_stool_scuz", ["price"] = 700, ["name"] = "Stool Scuz" },
	[24] = { ["object"] = "v_med_p_deskchair", ["price"] = 700, ["name"] = "Desk Chair" },
	[25] = { ["object"] = "v_med_p_easychair", ["price"] = 700, ["name"] = "Easy Chair" },
	[26] = { ["object"] = "v_med_whickerchair1", ["price"] = 700, ["name"] = "Whicker Chair" },
	[27] = { ["object"] = "prop_direct_chair_01", ["price"] = 700, ["name"] = "Direct Chair 1" },
	[28] = { ["object"] = "prop_direct_chair_02", ["price"] = 700, ["name"] = "Direct Chair 2" },
	[29] = { ["object"] = "prop_yacht_lounger", ["price"] = 700, ["name"] = "Yacht Seat 1" },
	[30] = { ["object"] = "prop_yacht_seat_01", ["price"] = 700, ["name"] = "Yacht Seat 2" },
	[31] = { ["object"] = "prop_yacht_seat_02", ["price"] = 700, ["name"] = "Yacht Seat 3" },
	[32] = { ["object"] = "prop_yacht_seat_03", ["price"] = 700, ["name"] = "Yacht Seat 4" },
	[33] = { ["object"] = "v_ret_chair_white", ["price"] = 100, ["name"] = "White Chair" },
	[34] = { ["object"] = "v_ret_chair", ["price"] = 100, ["name"] = "Chair" },
	[35] = { ["object"] = "v_ret_ta_stool", ["price"] = 100, ["name"] = "TA Stool" },
	[36] = { ["object"] = "prop_cs_office_chair", ["price"] = 100, ["name"] = "Office Chair" },
}

beds = {
	[1] = { ["object"] = "v_res_d_bed", ["price"] = 700, ["name"] = "D Bed" },	
	[2] = { ["object"] = "v_res_lestersbed", ["price"] = 700, ["name"] = "L Bed" },	
	[3] = { ["object"] = "v_res_mbbed", ["price"] = 700, ["name"] = "MB Bed" },	
	[4] = { ["object"] = "v_res_mdbed", ["price"] = 700, ["name"] = "MD Bed" },	
	[5] = { ["object"] = "v_res_msonbed", ["price"] = 700, ["name"] = "Mason Bed" },	
	[6] = { ["object"] = "v_res_tre_bed1", ["price"] = 700, ["name"] = "T Bed" },	
	[7] = { ["object"] = "v_res_tre_bed2", ["price"] = 700, ["name"] = "T Bed 2" },	
	[8] = { ["object"] = "v_res_tt_bed", ["price"] = 700, ["name"] = "TT Bed" },	
}


general = {
	[1] = { ["object"] = "v_corp_facebeanbag", ["price"] = 100, ["name"] = "Bean Bag 1" },
	[2] = { ["object"] = "v_res_cherubvase", ["price"] = 2500, ["name"] = "White Vase" },
	[3] = { ["object"] = "v_res_d_paddedwall", ["price"] = 300, ["name"] = "Padded Wall" },
	[4] = { ["object"] = "v_res_d_ramskull", ["price"] = 300, ["name"] = "Item" },
	[5] = { ["object"] = "v_res_d_whips", ["price"] = 300, ["name"] = "Whips" },
	[6] = { ["object"] = "v_res_fashmag1", ["price"] = 300, ["name"] = "Mags" },
	[7] = { ["object"] = "v_res_fashmagopen", ["price"] = 300, ["name"] = "Mags Open" },
	[8] = { ["object"] = "v_res_fa_magtidy", ["price"] = 300, ["name"] = "Mag Tidy" },
	[9] = { ["object"] = "v_res_fa_yogamat002", ["price"] = 300, ["name"] = "Yoga Mat 1" },
	[10] = { ["object"] = "v_res_fa_yogamat1", ["price"] = 300, ["name"] = "Yoga Mat 2" },
	[11] = { ["object"] = "v_res_fh_aftershavebox", ["price"] = 300, ["name"] = "Aftershave" },
	[12] = { ["object"] = "v_res_fh_flowersa", ["price"] = 300, ["name"] = "Flowers" },
	[13] = { ["object"] = "v_res_fh_fruitbowl", ["price"] = 300, ["name"] = "Fruitbowl" },
	[14] = { ["object"] = "v_res_fh_laundrybasket", ["price"] = 300, ["name"] = "Laundry Basket" },
	[15] = { ["object"] = "v_res_fh_pouf", ["price"] = 300, ["name"] = "Pouf" },
	[16] = { ["object"] = "v_res_fh_sculptmod", ["price"] = 300, ["name"] = "Sculpture" },
	[17] = { ["object"] = "v_res_j_magrack", ["price"] = 300, ["name"] = "Mag Rack" },
	[18] = { ["object"] = "v_res_jewelbox", ["price"] = 300, ["name"] = "Jewel Box" },
	[19] = { ["object"] = "v_res_mbbin", ["price"] = 300, ["name"] = "Bin" },
	[20] = { ["object"] = "v_res_mbowlornate", ["price"] = 300, ["name"] = "Ornate Bowl" },
	[21] = { ["object"] = "v_res_mbronzvase", ["price"] = 300, ["name"] = "Bronze Vase" },
	[22] = { ["object"] = "v_res_mchalkbrd", ["price"] = 300, ["name"] = "Chalk Board" },
	[23] = { ["object"] = "v_res_mddresser", ["price"] = 300, ["name"] = "Dresser" },
	[24] = { ["object"] = "v_res_mplinth", ["price"] = 300, ["name"] = "Linth" },
	[25] = { ["object"] = "v_res_mp_ashtrayb", ["price"] = 300, ["name"] = "Ashtray" },
	[26] = { ["object"] = "v_res_m_candle", ["price"] = 300, ["name"] = "Candle" },
	[27] = { ["object"] = "v_res_m_candlelrg", ["price"] = 300, ["name"] = "Candle Large" },
	[28] = { ["object"] = "v_res_m_kscales", ["price"] = 300, ["name"] = "Scales" },
	[29] = { ["object"] = "v_res_tt_bedpillow", ["price"] = 300, ["name"] = "Bed Pillow" },
}

general2 = {
	[1] = { ["object"] = "prop_a4_pile_01", ["price"] = 100, ["name"] = "A4 Pile" },
	[2] = { ["object"] = "prop_amb_40oz_03", ["price"] = 100, ["name"] = "40 oz" },
	[3] = { ["object"] = "prop_amb_beer_bottle", ["price"] = 100, ["name"] = "Beer" },
	[4] = { ["object"] = "prop_aviators_01", ["price"] = 100, ["name"] = "Aviators" },
	[5] = { ["object"] = "prop_barry_table_detail", ["price"] = 100, ["name"] = "Detail" },
	[6] = { ["object"] = "prop_beer_box_01", ["price"] = 100, ["name"] = "Beers" },
	[7] = { ["object"] = "prop_binoc_01", ["price"] = 100, ["name"] = "Binoculars" },
	[8] = { ["object"] = "prop_blox_spray", ["price"] = 100, ["name"] = "Blox Spray" },
	[9] = { ["object"] = "prop_bongos_01", ["price"] = 100, ["name"] = "Bongos" },
	[10] = { ["object"] = "prop_bong_01", ["price"] = 100, ["name"] = "Bong" },
	[11] = { ["object"] = "prop_boombox_01", ["price"] = 100, ["name"] = "Boombox" },
	[12] = { ["object"] = "prop_bowl_crisps", ["price"] = 100, ["name"] = "Bowl Crisps" },
	[13] = { ["object"] = "prop_candy_pqs", ["price"] = 100, ["name"] = "Candy" },
	[14] = { ["object"] = "prop_carrier_bag_01", ["price"] = 100, ["name"] = "Carrier bag" },
	[15] = { ["object"] = "prop_ceramic_jug_01", ["price"] = 100, ["name"] = "Ceramic Jug" },
	[16] = { ["object"] = "prop_cigar_pack_01", ["price"] = 100, ["name"] = "Cigar Pack 1" },
	[17] = { ["object"] = "prop_cigar_pack_02", ["price"] = 100, ["name"] = "Cigar Pack 2" },
	[18] = { ["object"] = "prop_cs_beer_box", ["price"] = 100, ["name"] = "Beer Box 2" },
	[19] = { ["object"] = "prop_cs_binder_01", ["price"] = 100, ["name"] = "Binder" },
	[20] = { ["object"] = "prop_cs_bs_cup", ["price"] = 100, ["name"] = "Cup" },
	[21] = { ["object"] = "prop_cs_cashenvelope", ["price"] = 100, ["name"] = "Envelope" },
	[22] = { ["object"] = "prop_cs_champ_flute", ["price"] = 100, ["name"] = "Flute" },
	[23] = { ["object"] = "prop_cs_duffel_01", ["price"] = 100, ["name"] = "Duffel Bag" },
	[24] = { ["object"] = "prop_cs_dvd", ["price"] = 50, ["name"] = "DVD" },
	[25] = { ["object"] = "prop_cs_dvd_case", ["price"] = 50, ["name"] = "DVD Case" },
	[26] = { ["object"] = "prop_cs_film_reel_01", ["price"] = 100, ["name"] = "Film Reel" },
	[27] = { ["object"] = "prop_cs_ilev_blind_01", ["price"] = 100, ["name"] = "Blind" },
	[28] = { ["object"] = "p_ld_bs_bag_01", ["price"] = 100, ["name"] = "Bag" },
	[29] = { ["object"] = "prop_cs_ironing_board", ["price"] = 100, ["name"] = "Ironing Board" },
	[30] = { ["object"] = "prop_cs_katana_01", ["price"] = 100, ["name"] = "Katana" },
	[31] = { ["object"] = "prop_cs_kettle_01", ["price"] = 100, ["name"] = "Kettle" },
	[32] = { ["object"] = "prop_cs_lester_crate", ["price"] = 100, ["name"] = "Crate" },
	[33] = { ["object"] = "prop_cs_petrol_can", ["price"] = 100, ["name"] = "Petrol Can" },
	[34] = { ["object"] = "prop_cs_sack_01", ["price"] = 100, ["name"] = "Sack" },
	[35] = { ["object"] = "prop_cs_script_bottle_01", ["price"] = 100, ["name"] = "Script Bottle" },
	[36] = { ["object"] = "prop_cs_script_bottle", ["price"] = 100, ["name"] = "Script Bottle 2" },
	[37] = { ["object"] = "prop_cs_street_binbag_01", ["price"] = 100, ["name"] = "Bin Bag" },
	[38] = { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 100, ["name"] = "Whiskey Bottle" },
	[39] = { ["object"] = "prop_sh_bong_01", ["price"] = 100, ["name"] = "Bong" },
	[40] = { ["object"] = "prop_peanut_bowl_01", ["price"] = 100, ["name"] = "Peanuts" },
	[41] = { ["object"] = "prop_tumbler_01", ["price"] = 100, ["name"] = "Tumbler" },

}
general3 = {
	[1] = { ["object"] = "v_ret_csr_bin", ["price"] = 100, ["name"] = "CSR Bin" },
	[2] = { ["object"] = "v_ret_fh_wickbskt", ["price"] = 100, ["name"] = "Basket" },
	[3] = { ["object"] = "v_ret_gc_bag01", ["price"] = 100, ["name"] = "GC Bag 1" },
	[4] = { ["object"] = "v_ret_gc_bag02", ["price"] = 100, ["name"] = "GC Bag 2" },
	[5] = { ["object"] = "v_ret_gc_bin", ["price"] = 100, ["name"] = "GC Bin" },
	[6] = { ["object"] = "v_ret_gc_cashreg", ["price"] = 100, ["name"] = "Cash Register" },
	[7] = { ["object"] = "v_ret_gc_chair01", ["price"] = 100, ["name"] = "GC Chair 01" },
	[8] = { ["object"] = "v_ret_gc_chair02", ["price"] = 100, ["name"] = "GC Chair 02" },
	[9] = { ["object"] = "v_ret_gc_clock", ["price"] = 100, ["name"] = "Clock" },
	[10] = { ["object"] = "v_ret_hd_prod1_", ["price"] = 100, ["name"] = "Prod 1" },
	[11] = { ["object"] = "v_ret_hd_prod2_", ["price"] = 100, ["name"] = "Prod 2" },
	[12] = { ["object"] = "v_ret_hd_prod3_", ["price"] = 100, ["name"] = "Prod 3" },
	[13] = { ["object"] = "v_ret_hd_prod4_", ["price"] = 100, ["name"] = "Prod 4" },
	[14] = { ["object"] = "v_ret_hd_prod5_", ["price"] = 100, ["name"] = "Prod 5" },
	[15] = { ["object"] = "v_ret_hd_prod6_", ["price"] = 100, ["name"] = "Prod 6" },
	[16] = { ["object"] = "v_ret_hd_unit1_", ["price"] = 100, ["name"] = "HD Unit 1" },
	[17] = { ["object"] = "v_ret_hd_unit2_", ["price"] = 100, ["name"] = "HD Unit 2" },
	[18] = { ["object"] = "v_ret_ml_fridge02", ["price"] = 100, ["name"] = "Fridge" },
	[19] = { ["object"] = "v_ret_ps_bag_01", ["price"] = 100, ["name"] = "Bag 1" },
	[20] = { ["object"] = "v_ret_ps_bag_02", ["price"] = 100, ["name"] = "Bag 2" },
	[21] = { ["object"] = "v_ret_ta_book1", ["price"] = 100, ["name"] = "Book 1" },
	[22] = { ["object"] = "v_ret_ta_book2", ["price"] = 100, ["name"] = "Book 2" },
	[23] = { ["object"] = "v_ret_ta_book3", ["price"] = 100, ["name"] = "Book 3" },
	[24] = { ["object"] = "v_ret_ta_book4", ["price"] = 100, ["name"] = "Book 4" },
	[25] = { ["object"] = "v_ret_ta_camera", ["price"] = 100, ["name"] = "Cam" },
	[26] = { ["object"] = "v_ret_ta_firstaid", ["price"] = 100, ["name"] = "First Aid" },
	[27] = { ["object"] = "v_ret_ta_hero", ["price"] = 100, ["name"] = "Hero" },
	[28] = { ["object"] = "v_ret_ta_mag1", ["price"] = 100, ["name"] = "Mag 1" },
	[29] = { ["object"] = "v_ret_ta_mag2", ["price"] = 100, ["name"] = "Mag 2" },
	[30] = { ["object"] = "v_ret_ta_skull", ["price"] = 100, ["name"] = "Skull" },
	[31] = { ["object"] = "prop_acc_guitar_01", ["price"] = 100, ["name"] = "Guitar" },
	[32] = { ["object"] = "prop_amb_handbag_01", ["price"] = 100, ["name"] = "Handbag" },
	[33] = { ["object"] = "prop_attache_case_01", ["price"] = 100, ["name"] = "Case" },
	[34] = { ["object"] = "prop_big_bag_01", ["price"] = 100, ["name"] = "Big Bag" },
	[35] = { ["object"] = "prop_bonesaw", ["price"] = 100, ["name"] = "Bonesaw" },
	[36] = { ["object"] = "prop_cs_fertilizer", ["price"] = 100, ["name"] = "Fertilizer" },
	[37] = { ["object"] = "prop_cs_shopping_bag", ["price"] = 100, ["name"] = "Shopping Bag" },
	[38] = { ["object"] = "prop_cs_vial_01", ["price"] = 100, ["name"] = "Vial" },
	[39] = { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 100, ["name"] = "Ragdoll" }, 
}
general4 = {
	[1] = { ["object"] = "prop_dummy_01", ["price"] = 100, ["name"] = "Dummy" },
	[2] = { ["object"] = "prop_egg_clock_01", ["price"] = 100, ["name"] = "Egg Clock" },
	[3] = { ["object"] = "prop_el_guitar_01", ["price"] = 100, ["name"] = "E Guitar 1" },
	[4] = { ["object"] = "prop_el_guitar_02", ["price"] = 100, ["name"] = "E Guitar 2" },
	[5] = { ["object"] = "prop_el_guitar_03", ["price"] = 100, ["name"] = "E Guitar 2" },
	[6] = { ["object"] = "prop_feed_sack_01", ["price"] = 100, ["name"] = "Feed Sack" },
	[7] = { ["object"] = "prop_floor_duster_01", ["price"] = 100, ["name"] = "Floor Duster" },
	[8] = { ["object"] = "prop_fruit_basket", ["price"] = 100, ["name"] = "Fruit Basket" },
	[9] = { ["object"] = "prop_f_duster_02", ["price"] = 100, ["name"] = "Duster" },
	[10] = { ["object"] = "prop_grapes_02", ["price"] = 100, ["name"] = "Grapes" },
	[11] = { ["object"] = "prop_hotel_clock_01", ["price"] = 100, ["name"] = "Hotel Clock" },
	[12] = { ["object"] = "prop_idol_case_01", ["price"] = 100, ["name"] = "Idol Case" },
	[13] = { ["object"] = "prop_jewel_02a", ["price"] = 100, ["name"] = "Jewels" },
	[14] = { ["object"] = "prop_jewel_02b", ["price"] = 100, ["name"] = "Jewels" },
	[15] = { ["object"] = "prop_jewel_02c", ["price"] = 100, ["name"] = "Jewels" },
	[16] = { ["object"] = "prop_jewel_03a", ["price"] = 100, ["name"] = "Jewels" },
	[17] = { ["object"] = "prop_jewel_03b", ["price"] = 100, ["name"] = "Jewels" },
	[18] = { ["object"] = "prop_jewel_04a", ["price"] = 100, ["name"] = "Jewels" },
	[19] = { ["object"] = "prop_jewel_04b", ["price"] = 100, ["name"] = "Jewels" },
	[20] = { ["object"] = "prop_j_disptray_01", ["price"] = 100, ["name"] = "Display Tray" },
	[21] = { ["object"] = "prop_j_disptray_01b", ["price"] = 100, ["name"] = "Display Tray" },
	[22] = { ["object"] = "prop_j_disptray_02", ["price"] = 100, ["name"] = "Display Tray" },
	[23] = { ["object"] = "prop_j_disptray_03", ["price"] = 100, ["name"] = "Display Tray" },
	[24] = { ["object"] = "prop_j_disptray_04", ["price"] = 100, ["name"] = "Display Tray" },
	[25] = { ["object"] = "prop_j_disptray_04b", ["price"] = 100, ["name"] = "Display Tray" },
	[26] = { ["object"] = "prop_j_disptray_05", ["price"] = 100, ["name"] = "Display Tray" },
	[27] = { ["object"] = "prop_j_disptray_05b", ["price"] = 100, ["name"] = "Display Tray" },
	[28] = { ["object"] = "prop_ld_greenscreen_01", ["price"] = 100, ["name"] = "Green Screen" },
	[29] = { ["object"] = "prop_ld_handbag", ["price"] = 100, ["name"] = "Handbag" },
	[30] = { ["object"] = "prop_ld_jerrycan_01", ["price"] = 100, ["name"] = "Jerry Can" },
	[31] = { ["object"] = "prop_ld_keypad_01", ["price"] = 100, ["name"] = "Keypad 1" },
	[32] = { ["object"] = "prop_ld_keypad_01b", ["price"] = 100, ["name"] = "Keypad 2" },
	[33] = { ["object"] = "prop_ld_suitcase_01", ["price"] = 100, ["name"] = "Suitcase 1" },
	[34] = { ["object"] = "prop_ld_suitcase_02", ["price"] = 100, ["name"] = "Suitcase 2" },
	[35] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 100, ["name"] = "Suitcase 3"},
	[36] = { ["object"] = "prop_mr_rasberryclean", ["price"] = 100, ["name"] = "Rasberry Clean" },
	[37] = { ["object"] = "prop_paper_bag_01", ["price"] = 100, ["name"] = "Paper Bag" },
	[38] = { ["object"] = "prop_shopping_bags01", ["price"] = 100, ["name"] = "Shopping Bags" },
	[39] = { ["object"] = "prop_shopping_bags02", ["price"] = 100, ["name"] = "Shopping Bags 2" },
	[40] = { ["object"] = "prop_yoga_mat_01", ["price"] = 100, ["name"] = "Yoga Mat 1" },
	[41] = { ["object"] = "prop_yoga_mat_02", ["price"] = 100, ["name"] = "Yoga Mat 2" },
	[42] = { ["object"] = "prop_yoga_mat_03", ["price"] = 100, ["name"] = "Yoga Mat 3" },
	[43] = { ["object"] = "p_ld_sax", ["price"] = 100, ["name"] = "Sax" },
	[44] = { ["object"] = "p_ld_soc_ball_01", ["price"] = 100, ["name"] = "SOCCER Ball" },
	[45] = { ["object"] = "p_watch_01", ["price"] = 100, ["name"] = "Watch 1" },
	[46] = { ["object"] = "p_watch_02", ["price"] = 100, ["name"] = "Watch 2" },
	[47] = { ["object"] = "p_watch_03", ["price"] = 100, ["name"] = "Watch 3" },
	[48] = { ["object"] = "p_watch_04", ["price"] = 100, ["name"] = "Watch 4" },
	[49] = { ["object"] = "p_watch_05", ["price"] = 100, ["name"] = "Watch 5" },
	[51] = { ["object"] = "p_watch_06", ["price"] = 100, ["name"] = "Watch 6" },
}

small = {
	[1] = { ["object"] = "v_res_r_figcat", ["price"] = 300, ["name"] = "Fig Cat" },
	[2] = { ["object"] = "v_res_r_figclown", ["price"] = 300, ["name"] = "Fig Clown" },
	[3] = { ["object"] = "v_res_r_figauth2", ["price"] = 300, ["name"] = "Fig Auth" },
	[4] = { ["object"] = "v_res_r_figfemale", ["price"] = 300, ["name"] = "Fig Female" },
	[5] = { ["object"] = "v_res_r_figflamenco", ["price"] = 300, ["name"] = "Fig Flamenco" },
	[6] = { ["object"] = "v_res_r_figgirl", ["price"] = 300, ["name"] = "Fig Girl" },
	[7] = { ["object"] = "v_res_r_figgirlclown", ["price"] = 300, ["name"] = "Fig Girl Clown" },
	[8] = { ["object"] = "v_res_r_figoblisk", ["price"] = 300, ["name"] = "Fig Oblisk" },
	[9] = { ["object"] = "v_res_r_figpillar", ["price"] = 300, ["name"] = "Fig Pillar" },
	[10] = { ["object"] = "v_res_r_teapot", ["price"] = 300, ["name"] = "Teapot" },
	[11] = { ["object"] = "v_res_sculpt_dec", ["price"] = 300, ["name"] = "Sculpture 1" },
	[12] = { ["object"] = "v_res_sculpt_decd", ["price"] = 300, ["name"] = "Sculpture 2" },
	[13] = { ["object"] = "v_res_sculpt_dece", ["price"] = 300, ["name"] = "Sculpture 3" },
	[14] = { ["object"] = "v_res_sculpt_decf", ["price"] = 300, ["name"] = "Sculpture 4" },
	[15] = { ["object"] = "v_res_skateboard", ["price"] = 300, ["name"] = "Skateboard" },
	[16] = { ["object"] = "v_res_sketchpad", ["price"] = 300, ["name"] = "Sketchpad" },
	[17] = { ["object"] = "v_res_tissues", ["price"] = 300, ["name"] = "Tissues" },
	[18] = { ["object"] = "v_res_tre_basketmess", ["price"] = 300, ["name"] = "Basket" },
	[19] = { ["object"] = "v_res_tre_bin", ["price"] = 300, ["name"] = "Bin" },
	[20] = { ["object"] = "v_res_tre_cushiona", ["price"] = 300, ["name"] = "Cushion 1" },
	[21] = { ["object"] = "v_res_tre_cushionb", ["price"] = 300, ["name"] = "Cushion 2" },
	[22] = { ["object"] = "v_res_tre_cushionc", ["price"] = 300, ["name"] = "Cushion 3" },
	[23] = { ["object"] = "v_res_tre_cushiond", ["price"] = 300, ["name"] = "Cushion 4" },
	[24] = { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 300, ["name"] = "Cushion 5" },
	[25] = { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 300, ["name"] = "Cushion 6" },
	[26] = { ["object"] = "v_res_tre_fruitbowl", ["price"] = 300, ["name"] = "Fruitbowl" },
	[27] = { ["object"] = "v_med_p_sideboard", ["price"] = 300, ["name"] = "Sideboard" },
	[28] = { ["object"] = "prop_idol_01", ["price"] = 100, ["name"] = "Idol 1" },
	

}

storage = {
	[1] = { ["object"] = "v_res_cabinet", ["price"] = 2500, ["name"] = "Cabinet Large" },
	[2] = { ["object"] = "v_res_d_dressingtable", ["price"] = 2500, ["name"] = "Dressing Table" },
	[3] = { ["object"] = "v_res_d_sideunit", ["price"] = 2500, ["name"] = "Side Unit" },
	[4] = { ["object"] = "v_res_fh_sidebrddine", ["price"] = 2500, ["name"] = "Side Unit" },
	[5] = { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 2500, ["name"] = "Side Unit" },
	[6] = { ["object"] = "v_res_mbbedtable", ["price"] = 2500, ["name"] = "Bed Unit" },
	[7] = { ["object"] = "v_res_j_tvstand", ["price"] = 2500, ["name"] = "Tv Unit" },
	[8] = { ["object"] = "v_res_mbdresser", ["price"] = 2500, ["name"] = "Dresser Unit" },
	[9] = { ["object"] = "v_res_mbottoman", ["price"] = 2500, ["name"] = "Bottoman Unit" },
	[10] = { ["object"] = "v_res_mconsolemod", ["price"] = 2500, ["name"] = "Console Unit" },
	[11] = { ["object"] = "v_res_mcupboard", ["price"] = 2500, ["name"] = "Cupboard Unit" },
	[12] = { ["object"] = "v_res_mdchest", ["price"] = 2500, ["name"] = "Chest Unit" },
	[13] = { ["object"] = "v_res_msoncabinet", ["price"] = 2500, ["name"] = "Mason Unit" },
	[14] = { ["object"] = "v_res_m_armoire", ["price"] = 2500, ["name"] = "Armoire Unit" },
	[15] = { ["object"] = "v_res_m_sidetable", ["price"] = 2500, ["name"] = "Side Unit" },
	[16] = { ["object"] = "v_res_son_desk", ["price"] = 2500, ["name"] = "Desk Unit" },
	[17] = { ["object"] = "v_res_tre_bedsidetable", ["price"] = 2500, ["name"] = "Side Unit" },
	[18] = { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 2500, ["name"] = "Side Unit 2" },
	[19] = { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 2500, ["name"] = "Book Unit" },
	[20] = { ["object"] = "v_res_tre_storagebox", ["price"] = 2500, ["name"] = "Box Unit" },
	[21] = { ["object"] = "v_res_tre_storageunit", ["price"] = 2500, ["name"] = "Storage Unit" },
	[22] = { ["object"] = "v_res_tre_wardrobe", ["price"] = 2500, ["name"] = "Wardrobe Unit" },
	[23] = { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 2500, ["name"] = "Wood Unit" },
	[24] = { ["object"] = "prop_devin_box_closed", ["price"] = 100, ["name"] = "Bean Bag 1" },
	[25] = { ["object"] = "prop_mil_crate_01", ["price"] = 100, ["name"] = "Mil Crate 1" },
	[26] = { ["object"] = "prop_mil_crate_02", ["price"] = 100, ["name"] = "Mil Crate 2" },
	[27] = { ["object"] = "prop_ld_int_safe_01", ["price"] = 1100, ["name"] = "Safe" },
}

electronics = {
	[1] = { ["object"] = "prop_trailr_fridge", ["price"] = 300, ["name"] = "Old Fridge" },
	[2] = { ["object"] = "v_res_fh_speaker", ["price"] = 300, ["name"] = "Speaker" },
	[3] = { ["object"] = "v_res_fh_speakerdock", ["price"] = 300, ["name"] = "Speaker Dock" },
	[4] = { ["object"] = "v_res_fh_bedsideclock", ["price"] = 300, ["name"] = "Bedside Clock" },
	[5] = { ["object"] = "v_res_fa_phone", ["price"] = 300, ["name"] = "Phone" },
	[6] = { ["object"] = "v_res_fh_towerfan", ["price"] = 300, ["name"] = "Tower Fan" },
	[7] = { ["object"] = "v_res_fa_fan", ["price"] = 300, ["name"] = "Fan" },
	[8] = { ["object"] = "v_res_lest_bigscreen", ["price"] = 300, ["name"] = "Bigscreen" },
	[9] = { ["object"] = "v_res_lest_monitor", ["price"] = 300, ["name"] = "Monitor" },
	[10] = { ["object"] = "v_res_tre_mixer", ["price"] = 300, ["name"] = "Mixer" },
	[11] = { ["object"] = "prop_cs_cctv", ["price"] = 100, ["name"] = "CCTV" },
	[12] = { ["object"] = "prop_ld_lap_top", ["price"] = 100, ["name"] = "Laptop" },
	[13] = { ["object"] = "prop_ld_monitor_01", ["price"] = 100, ["name"] = "Monitor" },

}


lighting = {
	[1] = { ["object"] = "v_corp_cd_desklamp", ["price"] = 100, ["name"] = "Desk Corp Lamp" },
	[2] = { ["object"] = "v_res_desklamp", ["price"] = 100, ["name"] = "Desk Lamp" },
	[3] = { ["object"] = "v_res_d_lampa", ["price"] = 100, ["name"] = "Lamp AA" },
	[4] = { ["object"] = "v_res_fa_lamp1on", ["price"] = 100, ["name"] = "Lamp 1" },
	[5] = { ["object"] = "v_res_fh_floorlamp", ["price"] = 100, ["name"] = "Floor Lamp" },
	[6] = { ["object"] = "v_res_fh_lampa_on", ["price"] = 100, ["name"] = "Lamp 2" },
	[7] = { ["object"] = "v_res_j_tablelamp1", ["price"] = 100, ["name"] = "Table Lamp" },
	[8] = { ["object"] = "v_res_j_tablelamp2", ["price"] = 100, ["name"] = "Table Lamp 2" },
	[9] = { ["object"] = "v_res_mdbedlamp", ["price"] = 100, ["name"] = "Bed Lamp" },
	[10] = { ["object"] = "v_res_mplanttongue", ["price"] = 100, ["name"] = "Plant Tongue Lamp" },
	[11] = { ["object"] = "v_res_mtblelampmod", ["price"] = 100, ["name"] = "Table Lamp 3" },
	[12] = { ["object"] = "v_res_m_lampstand", ["price"] = 100, ["name"] = "Lamp Stand" },
	[13] = { ["object"] = "v_res_m_lampstand2", ["price"] = 100, ["name"] = "Lamp Stand 2" },
	[14] = { ["object"] = "v_res_m_lamptbl", ["price"] = 100, ["name"] = "Table Lamp 4" },
	[15] = { ["object"] = "v_res_tre_lightfan", ["price"] = 100, ["name"] = "Light Fan" },
	[16] = { ["object"] = "v_res_tre_talllamp", ["price"] = 100, ["name"] = "Tall Lamp" },
	[17] = { ["object"] = "v_ret_fh_walllighton", ["price"] = 100, ["name"] = "Wall Light" },
	[18] = { ["object"] = "v_ret_gc_lamp", ["price"] = 100, ["name"] = "GC Lamp" },

	[19] = { ["object"] = "prop_dummy_light", ["price"] = 100, ["name"] = "Flickering Light" },
	[20] = { ["object"] = "prop_ld_cont_light_01", ["price"] = 100, ["name"] = "Side Wall Light" },
	[21] = { ["object"] = "V_44_D_emis", ["price"] = 100, ["name"] = "Test Light" },



}


tables = {
	[1] = { ["object"] = "v_res_d_coffeetable", ["price"] = 500, ["name"] = "Coffee Table 1" },
	[2] = { ["object"] = "v_res_d_roundtable", ["price"] = 500, ["name"] = "Round Table" },
	[3] = { ["object"] = "v_res_d_smallsidetable", ["price"] = 500, ["name"] = "Small Side Table" },
	[4] = { ["object"] = "v_res_fh_coftablea", ["price"] = 500, ["name"] = "Table A" },
	[5] = { ["object"] = "v_res_fh_coftableb", ["price"] = 500, ["name"] = "Table B" },
	[6] = { ["object"] = "v_res_fh_coftbldisp", ["price"] = 500, ["name"] = "Table C" },
	[7] = { ["object"] = "v_res_fh_diningtable", ["price"] = 500, ["name"] = "Dining Table" },
	[8] = { ["object"] = "v_res_j_coffeetable", ["price"] = 500, ["name"] = "Coffee Table 2" },
	[9] = { ["object"] = "v_res_j_lowtable", ["price"] = 500, ["name"] = "Low Table" },
	[10] = { ["object"] = "v_res_mdbedtable", ["price"] = 500, ["name"] = "Bed Table" },
	[11] = { ["object"] = "v_res_mddesk", ["price"] = 500, ["name"] = "Desk" },
	[12] = { ["object"] = "v_res_msidetblemod", ["price"] = 500, ["name"] = "Side Table" },
	[13] = { ["object"] = "v_res_m_console", ["price"] = 500, ["name"] = "Console Table" },
	[14] = { ["object"] = "v_res_m_dinetble_replace", ["price"] = 500, ["name"] = "Dining Table 2" },
	[15] = { ["object"] = "v_res_m_h_console", ["price"] = 500, ["name"] = "Console H Table" },
	[16] = { ["object"] = "v_res_m_stool", ["price"] = 500, ["name"] = "Stool?" },
	[17] = { ["object"] = "v_res_tre_sideboard", ["price"] = 500, ["name"] = "Sideboard Table" },
	[18] = { ["object"] = "v_res_tre_table2", ["price"] = 500, ["name"] = "Table 2" },
	[19] = { ["object"] = "v_res_tre_tvstand", ["price"] = 500, ["name"] = "Tv Table" },
	[20] = { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 500, ["name"] = "Tv Table Tall" },
	[21] = { ["object"] = "v_med_p_coffeetable", ["price"] = 500, ["name"] = "Med Coffee Table" },
	[22] = { ["object"] = "v_med_p_desk", ["price"] = 500, ["name"] = "Med Desk" },
	[23] = { ["object"] = "prop_yacht_table_01", ["price"] = 100, ["name"] = "Yacht Table 1" },
	[24] = { ["object"] = "prop_yacht_table_02", ["price"] = 100, ["name"] = "Yacht Table 2" },
	[25] = { ["object"] = "prop_yacht_table_03", ["price"] = 100, ["name"] = "Yacht Table 3" },
	[26] = { ["object"] = "v_ret_csr_table", ["price"] = 100, ["name"] = "CSR Table" },

}

plants = {
	[1] = { ["object"] = "prop_fib_plant_01", ["price"] = 150, ["name"] = "Plant Fib" },
	[2] = { ["object"] = "v_corp_bombplant", ["price"] = 170, ["name"] = "Plant Bomb" },		
	[3] = { ["object"] = "v_res_mflowers", ["price"] = 170, ["name"] = "Plant Flowers" },	
	[4] = { ["object"] = "v_res_mvasechinese", ["price"] = 170, ["name"] = "Plant Chinese" },	
	[5] = { ["object"] = "v_res_m_bananaplant", ["price"] = 170, ["name"] = "Plant Banana" },	
	[6] = { ["object"] = "v_res_m_palmplant1", ["price"] = 170, ["name"] = "Plant Palm" },	
	[7] = { ["object"] = "v_res_m_palmstairs", ["price"] = 170, ["name"] = "Plant Palm 2" },	
	[8] = { ["object"] = "v_res_m_urn", ["price"] = 170, ["name"] = "Plant Urn" },	
	[9] = { ["object"] = "v_res_rubberplant", ["price"] = 170, ["name"] = "Plant Rubber" },	
	[10] = { ["object"] = "v_res_tre_plant", ["price"] = 170, ["name"] = "Plant" },	
	[11] = { ["object"] = "v_res_tre_tree", ["price"] = 170, ["name"] = "Plant Tree" },	
	[12] = { ["object"] = "v_med_p_planter", ["price"] = 170, ["name"] = "Planter" },	
	[13] = { ["object"] = "v_ret_flowers", ["price"] = 100, ["name"] = "Flowers" },
	[14] = { ["object"] = "v_ret_j_flowerdisp", ["price"] = 100, ["name"] = "Flowers 1" },
	[15] = { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 100, ["name"] = "Flowers 2" },
}

kitchen = {
	[1] = { ["object"] = "prop_washer_01", ["price"] = 150, ["name"] = "Washer 1" },
	[2] = { ["object"] = "prop_washer_02", ["price"] = 150, ["name"] = "Washer 2" },
	[3] = { ["object"] = "prop_washer_03", ["price"] = 150, ["name"] = "Washer 3" },
	[4] = { ["object"] = "prop_washing_basket_01", ["price"] = 150, ["name"] = "Washing Basket" },
	[5] = { ["object"] = "v_res_fridgemoda", ["price"] = 150, ["name"] = "Fridge 1" },
	[6] = { ["object"] = "v_res_fridgemodsml", ["price"] = 150, ["name"] = "Fridge 2" },
	[7] = { ["object"] = "prop_fridge_01", ["price"] = 150, ["name"] = "Fridge 3" },
	[8] = { ["object"] = "prop_fridge_03", ["price"] = 150, ["name"] = "Fridge 4" },
	[9] = { ["object"] = "prop_cooker_03", ["price"] = 150, ["name"] = "Cooker" },
	[10] = { ["object"] = "prop_micro_01", ["price"] = 150, ["name"] = "Microwave 1" },
	[11] = { ["object"] = "prop_micro_02", ["price"] = 150, ["name"] = "Microwave 2" },
	[12] = { ["object"] = "prop_wok", ["price"] = 150, ["name"] = "Wok" },
	[13] = { ["object"] = "v_res_cakedome", ["price"] = 150, ["name"] = "Cake Plate" },
	[14] = { ["object"] = "v_res_fa_chopbrd", ["price"] = 150, ["name"] = "Chopping Board" },
	[15] = { ["object"] = "v_res_mutensils", ["price"] = 150, ["name"] = "Utensils" },
	[16] = { ["object"] = "v_res_pestle", ["price"] = 150, ["name"] = "Pestle" },
	[17] = { ["object"] = "v_ret_ta_paproll", ["price"] = 150, ["name"] = "PaperRoll 1" },
	[18] = { ["object"] = "v_ret_ta_paproll2", ["price"] = 150, ["name"] = "PaperRoll 2" },
	[19] = { ["object"] = "v_ret_fh_pot01", ["price"] = 150, ["name"] = "Pot 1" },
	[20] = { ["object"] = "v_ret_fh_pot02", ["price"] = 150, ["name"] = "Pot 2" },
	[21] = { ["object"] = "v_ret_fh_pot05", ["price"] = 150, ["name"] = "Pot 3" },
	[22] = { ["object"] = "prop_pot_03", ["price"] = 150, ["name"] = "Pot 4" },
	[23] = { ["object"] = "prop_pot_04", ["price"] = 150, ["name"] = "Pot 5" },
	[24] = { ["object"] = "prop_pot_05", ["price"] = 150, ["name"] = "Pot 6" },
	[25] = { ["object"] = "prop_pot_06", ["price"] = 150, ["name"] = "Pot 7" },
	[26] = { ["object"] = "prop_pot_rack", ["price"] = 150, ["name"] = "Pot Rack" },
	[27] = { ["object"] = "prop_kitch_juicer", ["price"] = 150, ["name"] = "Juicer" },

}


bathroom = {
	[1] = { ["object"] = "prop_ld_toilet_01", ["price"] = 100, ["name"] = "Toilet 1" },
	[2] = { ["object"] = "prop_toilet_01", ["price"] = 100, ["name"] = "Toilet 2" },
	[3] = { ["object"] = "prop_toilet_02", ["price"] = 100, ["name"] = "Toilet 3" },
	[4] = { ["object"] = "prop_sink_02", ["price"] = 100, ["name"] = "Sink 1" },
	[5] = { ["object"] = "prop_sink_04", ["price"] = 100, ["name"] = "Sink 2" },
	[6] = { ["object"] = "prop_sink_05", ["price"] = 100, ["name"] = "Sink 3" },
	[7] = { ["object"] = "prop_sink_06", ["price"] = 100, ["name"] = "Sink 4" },
	[8] = { ["object"] = "prop_soap_disp_01", ["price"] = 100, ["name"] = "Soap Dispenser" },
	[9] = { ["object"] = "prop_shower_rack_01", ["price"] = 100, ["name"] = "Shower Rack" },
	[10] = { ["object"] = "prop_handdry_01", ["price"] = 100, ["name"] = "Hand Dryer 1" },
	[11] = { ["object"] = "prop_handdry_02", ["price"] = 100, ["name"] = "Hand Dryer 2" },
	[12] = { ["object"] = "prop_towel_rail_01", ["price"] = 100, ["name"] = "Towel Rail 1" },
	[13] = { ["object"] = "prop_towel_rail_02", ["price"] = 100, ["name"] = "Towel Rail 2" },
	[14] = { ["object"] = "prop_towel_01", ["price"] = 100, ["name"] = "Towel 1" },
	[15] = { ["object"] = "v_res_mbtowel", ["price"] = 100, ["name"] = "Towel 2" },
	[16] = { ["object"] = "v_res_mbtowelfld", ["price"] = 100, ["name"] = "Towel 3" },
	[17] = { ["object"] = "v_res_mbath", ["price"] = 100, ["name"] = "Bath" },
	[18] = { ["object"] = "v_res_mbsink", ["price"] = 100, ["name"] = "Sink" },

}

medical = {
	[1] = { ["object"] = "v_med_barrel", ["price"] = 750, ["name"] = "Barrel" },
	[2] = { ["object"] = "v_med_apecrate", ["price"] = 750, ["name"] = "Ape Crate" },
	[3] = { ["object"] = "v_med_apecratelrg", ["price"] = 750, ["name"] = "Ape Crate Large" },
	[4] = { ["object"] = "v_med_bed1", ["price"] = 750, ["name"] = "Bed 1" },
	[5] = { ["object"] = "v_med_bed2", ["price"] = 750, ["name"] = "Bed 2" },
	[6] = { ["object"] = "v_med_bedtable", ["price"] = 750, ["name"] = "Bed Table" },
	[7] = { ["object"] = "v_med_bench1", ["price"] = 750, ["name"] = "Bench 1" },
	[8] = { ["object"] = "v_med_bench2", ["price"] = 750, ["name"] = "Bench 2" },
	[9] = { ["object"] = "v_med_benchcentr", ["price"] = 750, ["name"] = "Bench Center" },
	[10] = { ["object"] = "v_med_benchset1", ["price"] = 750, ["name"] = "Bench Set" },
	[11] = { ["object"] = "v_med_bigtable", ["price"] = 750, ["name"] = "Big Table" },
	[12] = { ["object"] = "v_med_bin", ["price"] = 150, ["name"] = "Bin" },
	[13] = { ["object"] = "v_med_centrifuge1", ["price"] = 750, ["name"] = "Centrifuge" },
	[14] = { ["object"] = "v_med_cooler", ["price"] = 750, ["name"] = "Cooler" },
	[15] = { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 750, ["name"] = "Monitor" },
	[16] = { ["object"] = "v_med_cor_autopsytbl", ["price"] = 750, ["name"] = "Autopsy Table" },
	[17] = { ["object"] = "v_med_cor_cembin", ["price"] = 750, ["name"] = "Bin" },
	[18] = { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 750, ["name"] = "Trolley" },
	[19] = { ["object"] = "v_med_cor_chemical", ["price"] = 750, ["name"] = "Chem" },
	[20] = { ["object"] = "v_med_cor_emblmtable", ["price"] = 750, ["name"] = "BLM Table" },
	[21] = { ["object"] = "v_med_cor_fileboxa", ["price"] = 750, ["name"] = "File Box" },
	[22] = { ["object"] = "v_med_cor_filingcab", ["price"] = 750, ["name"] = "File Cab" },
	[23] = { ["object"] = "v_med_cor_hose", ["price"] = 750, ["name"] = "Hose" },
	[24] = { ["object"] = "v_med_cor_largecupboard", ["price"] = 750, ["name"] = "Large Cupboard" },
	[25] = { ["object"] = "v_med_cor_lightbox", ["price"] = 750, ["name"] = "Lightbox" },
	[26] = { ["object"] = "v_med_cor_medstool", ["price"] = 750, ["name"] = "Medstool" },
	[27] = { ["object"] = "v_med_cor_minifridge", ["price"] = 750, ["name"] = "Minifridge" },
	[28] = { ["object"] = "v_med_cor_papertowels", ["price"] = 750, ["name"] = "Papertowels" },
	[29] = { ["object"] = "v_med_cor_photocopy", ["price"] = 750, ["name"] = "Photocopy" },
	[30] = { ["object"] = "v_med_cor_tvstand", ["price"] = 750, ["name"] = "TV Stand" },
	[31] = { ["object"] = "v_med_cor_wallunita", ["price"] = 750, ["name"] = "Wall Unit" },
	[32] = { ["object"] = "v_med_examlight", ["price"] = 750, ["name"] = "Exam light" },
	[33] = { ["object"] = "v_med_gastank", ["price"] = 750, ["name"] = "Gas Tank" },
	[34] = { ["object"] = "v_med_hazmatscan", ["price"] = 750, ["name"] = "Hazmat Scan" },
	[35] = { ["object"] = "v_med_hospheadwall1", ["price"] = 750, ["name"] = "Head Wall" },
	[36] = { ["object"] = "v_med_hospseating1", ["price"] = 750, ["name"] = "Seating" },
	[37] = { ["object"] = "v_med_hosptable", ["price"] = 750, ["name"] = "Hosp Table" },
	[38] = { ["object"] = "v_med_latexgloveboxblue", ["price"] = 50, ["name"] = "Glove Box" },
	[39] = { ["object"] = "v_med_medwastebin", ["price"] = 750, ["name"] = "Wastebin" },
	[40] = { ["object"] = "v_med_oscillator3", ["price"] = 750, ["name"] = "Oscillator" },
	[41] = { ["object"] = "prop_ld_health_pack", ["price"] = 100, ["name"] = "Health Pack" },
}
